spring.datasource.url=jdbc:postgresql://localhost:5433/study_platform
spring.datasource.username=postgres
spring.datasource.password=sudo

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.cache=false

# Optional: Connection pool settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000

# XML/XSL configuration
app.xml.stylesheet-url=http://localhost:8080/xsl/study.xsl

#JMS configuration
#???????? embedded-?????
spring.artemis.mode=embedded
spring.artemis.embedded.enabled=true
spring.artemis.embedded.persistent=false

#?????? (pub-sub)
spring.artemis.embedded.topics=entity-changes-topic
spring.jms.pub-sub-domain=true
app.jms.entity-change-destination=entity-changes-topic

# ??? mailhog
spring.mail.host=localhost
spring.mail.port=1025 

spring.mail.username=
spring.mail.password=

spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

spring.mail.default-encoding=UTF-8

app.notification.recipients=dev@example.com


